////////////////////////////////////////////////////////////////////////////////////////
//	This structure was generated by the world-famous disastrous organization HellCo.  //
//	(c) HellCo 2012                                                                   //
////////////////////////////////////////////////////////////////////////////////////////



#pragma once

#pragma pack(push, 1)

struct FailuresStruct {
		struct TAircraftAndEngine {
			// Планер
			union TAirFrame {
				struct {
					unsigned char UpperInputOpenLh : 1; // Левый верхний вход открыт
					unsigned char FailureAirIntakeLh : 1; // Отказ левого воздухозаборника
					unsigned char UpperInputOpenRh : 1; // Правый верхний вход открыт
					unsigned char FailureAirIntakeRh : 1; // Отказ правого воздухозаборника
					unsigned char FlapsFail : 1; // Отказ закрылков
				};
				unsigned char alignment[1];
			} AirFrame;
			// Фонарь кабины
			union TCockpitCanopy {
			};
			// Система аварийного покидания самолета
			union TEmergencyEscapeSystem {
			};
			// Двигатель РД – 33 сер.2 (сер.3)
			union TEngine {
				struct {
					unsigned char FailureEngineLh : 1; // Отказ левого двигателя
					unsigned char FailureEngineRh : 1; // Отказ правого двигателя
					unsigned char EngineStartingDisplayLh : 1; // Не высвечивается табло ЗАПУСК ДВИГАТЕЛЯ левого двигателя
					unsigned char EngineStartingDisplayRh : 1; // Не высвечивается табло ЗАПУСК ДВИГАТЕЛЯ правого двигателя
					unsigned char DangerRegimeTS : 1; // Опасный режим турбостартера
					unsigned char RotorFailLh : 1; // Нет раскрутки ротора КВД левого двигателя
					unsigned char RotorFailRh : 1; // Нет раскрутки ротора КВД правого двигателя
					unsigned char FuelBurnFailLh : 1; // Нет воспламенения топлива в ОКС при запуске левого двигателя на земле
					unsigned char FuelBurnFailRh : 1; // Нет воспламенения топлива в ОКС при запуске правого двигателя на земле
					unsigned char StuckRpmLh : 1; // Зависание оборотов с увеличением температуры Т4 при запуске левого двигателя
					unsigned char StuckRpmRh : 1; // Зависание оборотов с увеличением температуры Т4 при запуске правого двигателя
					unsigned char TempIncreaseLh : 1; // Возрастание температуры газов левого двигателя выше допустимой
					unsigned char TempIncreaseRh : 1; // Возрастание температуры газов правого двигателя выше допустимой
					unsigned char BothEngineSpinning : 1; // Одновременная раскрутка обоих двигателей
					unsigned char FireLE : 1; // Пожар в отсеке левого двигателя
					unsigned char FireRE : 1; // Пожар в отсеке правого двигателя
					unsigned char SurgeLh : 1; // Помпаж левого двигателя
					unsigned char SurgeRh : 1; // Помпаж правого двигателя
					unsigned char DisconCtrlLh : 1; // Рассоединение тяг управления левым двигателем
					unsigned char DisconCtrlRh : 1; // Рассоединение тяг управления правым двигателем
					unsigned char StopEngineAutoStartLh : 1; // Самовыключение левого двигателя (автоматический запуск)
					unsigned char StopEngineSemiAutoStartLh : 1; // Самовыключение левого двигателя (полуавтоматический запуск)
					unsigned char StopEngineManualStartLh : 1; // Самовыключение левого двигателя (ручной запуск)
					unsigned char StopEngineAutoStartRh : 1; // Самовыключение правого двигателя (автоматический запуск)
					unsigned char StopEngineSemiAutoStartRh : 1; // Самовыключение правого двигателя (полуавтоматический запуск)
					unsigned char StopEngineManualStartRh : 1; // Самовыключение правого двигателя (ручной запуск)
					unsigned char FailOilSysHighTempLh : 1; // Отказ маслосистемы левого двигателя (температура масла выше допустимой)
					unsigned char FailOilSysLowPressureLh : 1; // Отказ маслосистемы левого двигателя (мало давление масла)
					unsigned char FailOilSysChipsLh : 1; // Отказ маслосистемы левого двигателя (стружка в масле)
					unsigned char FailOilSysHighTempRh : 1; // Отказ маслосистемы правого двигателя (температура масла выше допустимой)
					unsigned char FailOilSysLowPressureRh : 1; // Отказ маслосистемы правого двигателя (мало давление масла)
					unsigned char FailOilSysChipsRh : 1; // Отказ маслосистемы правого двигателя (стружка в масле)
					unsigned char FailTempControlSystemLh : 1; // Отказ системы регулирования температуры газов за турбиной и оборотов левого двигателя
					unsigned char FailTempControlSystemRh : 1; // Отказ системы регулирования температуры газов за турбиной и оборотов правого двигателя
					unsigned char SpontaneousShutdownABLh : 1; // Самопроизвольное отключение форсажа левого двигателя
					unsigned char SpontaneousShutdownABRh : 1; // Самопроизвольное отключение форсажа правого двигателя
					unsigned char EngHighSpeedLh : 1; // Обороты левого двигателя выше допустимых
					unsigned char EngHighSpeedRh : 1; // Обороты правого двигателя выше допустимых
					unsigned char EngHighVibrLh : 1; // Вибрация левого двигателя выше допустимых
					unsigned char EngHighVibrRh : 1; // Вибрация правого двигателя выше допустимых
					unsigned char EngOverheatLh : 1; // Перегрев левого двигателя
					unsigned char EngOverheatRh : 1; // Перегрев левого двигателя
					unsigned char DangerousFuelPressureLh : 1; // Опасное давление топлива левого двигателя
					unsigned char DangerousFuelPressureRh : 1; // Опасное давление топлива правого двигателя
					unsigned char AntiSurgeFailLh : 1; // Отказ АПЗ левого двигателя
					unsigned char AntiSurgeFailRh : 1; // Отказ АПЗ правого двигателя
					unsigned char AntiFreezingSystemFailLh : 1; // Отказ ПОС левого двигателя
					unsigned char AntiFreezingSystemFailRh : 1; // Отказ ПОС правого двигателя
					unsigned char EngineControlSystemFailLh : 1; // Система контроля левого двигателя
					unsigned char EngineControlSystemFailRh : 1; // Система контроля правого двигателя
				};
				unsigned char alignment[7];
			} Engine;
			// Коробка самолетных агрегатов КСА
			union TAircraftGearBox {
				struct {
					unsigned char FireGearBox : 1; // Пожар КСА
					unsigned char GearBoxVibr : 1; // Отказ КСА. Вибрация выше допустимой
					unsigned char GearBoxOilPressureLow : 1; // Отказ КСА. Мало давление масла
				};
				unsigned char alignment[1];
			} AircraftGearBox;
			// Газотурбинный двигатель – энергоузел ВК-100М
			union TGasTurbineEngine {
			};
			// Противопожарное оборудование
			union TExtinguishingEquipment {
			};
			// Система кондиционирования и охлаждения отсеков оборудования
			union TEquipmentConditioningCoolingSystem {
				struct {
					unsigned char CellCoolingFail : 1; // Нет охлаждения отсеков
				};
				unsigned char alignment[1];
			} EquipmentConditioningCoolingSystem;
			// Топливная система
			union TFuelSystem {
				struct {
					unsigned char DropOfFuelPressure : 1; // Падение давления топлива за подкачивающим насосом расходного бака
					unsigned char CheckFuelAmount : 1; // Проверь запас топлива
					unsigned char WDTpressFail : 1; // Нет наддува подкрыльевых баков
					unsigned char VTFuelConsFail : 1; // Нет выработки подфюзеляжного бака
					unsigned char NoInputFuelMeasuring : 1; // Нет контроля принимаемого топлива
					unsigned char LowFlowMeterAccuracy : 1; // Снижение точности расходомера
					unsigned char LowFuelGaugeAccuracy : 1; // Снижение точности топливомера
					unsigned char DisconRefuelProbe : 1; // Проведи расцепление
					unsigned char FuelLeak : 1; // Провышенный расход топлива (утечка)
				};
				unsigned char alignment[2];
			} FuelSystem;
			// Гидравлическая система
			union THydraulicSystem {
				struct {
					unsigned char MainHydraulicFailure : 1; // Отказ общей гидросистемы
					unsigned char BoosterHydraulicFailure : 1; // Отказ бустерной гидросистемы
				};
				unsigned char alignment[1];
			} HydraulicSystem;
			// Пневматическая система
			union TPneumaticSystem {
				struct {
					unsigned char MainPneumaticFailure : 1; // Отказ основной пневмосистемы
					unsigned char EmergencyPneumaticFailure : 1; // Отказ аварийной пневмосистемы
				};
				unsigned char alignment[1];
			} PneumaticSystem;
			// Система управления самолетом
			union TAircraftControlSystem {
			};
			// Система управления двигателями
			union TEngineControlSystem {
			};
			// Шасси
			union TUndercarriage {
				struct {
					unsigned char FailExtMainLGLeft : 1; // Невыход одной из основных опор шасси (левой)
					unsigned char FailExtMainLGRight : 1; // Невыход одной из основных опор шасси (правой)
					unsigned char FailExtTopLG : 1; // Невыход передней опоры шасси
					unsigned char AntiSkidFail : 1; // Отказ антиюзовой автоматики
					unsigned char NoseWheelSteeringFail : 1; // Отказ МРК
					unsigned char WheelAlarmFail : 1; // Отказ сигнализации шасси
				};
				unsigned char alignment[1];
			} Undercarriage;
			// Система парашютно-тормозная посадочная
			union TParachuteBrakingSystem {
				struct {
					unsigned char ChuteFailToDeploy : 1; // Невыход тормозного парашюта
				};
				unsigned char alignment[1];
			} ParachuteBrakingSystem;
			// Тормозная система
			union TBrakingSystem {
				struct {
					unsigned char BreakFail : 1; // Отказ основной системы торможения
				};
				unsigned char alignment[1];
			} BrakingSystem;
			// Система жидкостного охлаждения БРЛС и наддува блоков оборудования
			union TLocatorCoolingSystem {
			};
		} AircraftAndEngine;
		struct TAircraftArmament {
			// Информационно-вычислительный комплекс (ИВК-29)
			union TInformationComputingComplex {
				struct {
					unsigned char CompFail : 1; // Отказ двух БЦВМ ИВК
				};
				unsigned char alignment[1];
			} InformationComputingComplex;
			// Система управления оружием  -  СУО-29КИ
			union TWeaponControlSystem {
				struct {
					unsigned char FailWCS : 1; // Отказ СУО
					unsigned char UnlockSusp1 : 1; // Замок открыт ТП1
					unsigned char UnlockSusp2 : 1; // Замок открыт ТП2
					unsigned char UnlockSusp3 : 1; // Замок открыт ТП3
					unsigned char UnlockSusp4 : 1; // Замок открыт ТП4
					unsigned char UnlockSusp5 : 1; // Замок открыт ТП5
					unsigned char UnlockSusp6 : 1; // Замок открыт ТП6
					unsigned char SuspFail1 : 1; // Отказ ТП1
					unsigned char SuspFail2 : 1; // Отказ ТП2
					unsigned char SuspFail3 : 1; // Отказ ТП3
					unsigned char SuspFail4 : 1; // Отказ ТП4
					unsigned char SuspFail5 : 1; // Отказ ТП5
					unsigned char SuspFail6 : 1; // Отказ ТП6
				};
				unsigned char alignment[2];
			} WeaponControlSystem;
			// Оптико-локационная станция  -  ОЛС - УЭ
			union TOpticoLocationSystem {
				struct {
					unsigned char FailOLS : 1; // Отказ ОЛС
				};
				unsigned char alignment[1];
			} OpticoLocationSystem;
			// Нашлемная система целеуказания и индикации – DASH IV
			union THelmetAimingSystem {
				struct {
					unsigned char FailDASH : 1; // Отказ НСЦИ
				};
				unsigned char alignment[1];
			} HelmetAimingSystem;
			// Система создания пассивных помех
			union TJammingSystem {
				struct {
					unsigned char FailCMDS : 1; // Отказ СУВП
				};
				unsigned char alignment[1];
			} JammingSystem;
			// Система видеорегистрации цифровая
			union TDigitalVideoRecorderSystem {
			};
			// Артиллерийское вооружение  -  пушка ГШ-301
			union TArtilleryArmament {
				struct {
					unsigned char GunFail : 1; // Отказ ВПУ
				};
				unsigned char alignment[1];
			} ArtilleryArmament;
			// Универсальный имитатор УИ-АСП (ACMI)
			union TWeaponAircraftSimulator {
				struct {
					unsigned char FailACMI : 1; // Отказ ACMI
				};
				unsigned char alignment[1];
			} WeaponAircraftSimulator;
		} AircraftArmament;
		struct TAvionics {
			// Бортовая радиолокационная станция БРЛС «ЖУК МЭ» (FGM 229)
			union TRadioLocationSytem {
				struct {
					unsigned char RadarFail : 1; // Отказ БРЛС
					unsigned char RadarOverheat : 1; // Перегрев ЦВМ РЛС
					unsigned char RadarBitFail : 1; // Отказ ВСК РЛС
				};
				unsigned char alignment[1];
			} RadioLocationSytem;
			// Станция предупреждения об облучении (RWR) TARANG 1В
			union TRadarWarningSytem {
				struct {
					unsigned char FailRWR : 1; // Отказ RWR
				};
				unsigned char alignment[1];
			} RadarWarningSytem;
			// Радиовысотомер RАМ 1701 АС
			union TRadioAltimeter {
				struct {
					unsigned char FailRadAlt : 1; // Отказ РВ
				};
				unsigned char alignment[1];
			} RadioAltimeter;
			// Система тактической аэронавигации TACAN 2901АU
			union TTacticalNavigationSystem {
				struct {
					unsigned char FailTACAN : 1; // Отказ TACAN
					unsigned char FailTACANrange : 1; // Отказ дальности TACAN
				};
				unsigned char alignment[1];
			} TacticalNavigationSystem;
			// Многорежимный приемник VOR/ILS/MKR ANS 1100А
			union TMultiModeReceiver {
				struct {
					unsigned char FailMKR : 1; // Отказ MKR
					unsigned char FailILS : 1; // Отказ ILS
					unsigned char FailVOR : 1; // Отказ VOR
				};
				unsigned char alignment[1];
			} MultiModeReceiver;
			// Радиостанция Р-833Б
			union TRadioStation {
				struct {
					unsigned char COM1Fail : 1; // Отказ СОМ-1
					unsigned char COM2Fail : 1; // Отказ СОМ-2
					unsigned char DataLinkFail : 1; // Отказ Р-098-5
					unsigned char FailRCP : 1; // Отказ ОПУ
				};
				unsigned char alignment[1];
			} RadioStation;
			// Аппаратура передачи данных  Р-098- 5
			union TDataLinkEquipment {
			};
			// МС-2М в части АВСК
			union TInternalSwitchingEquipment {
				struct {
					unsigned char FailCVWScomp : 1; // Отказ СЦВМ МС2М
				};
				unsigned char alignment[1];
			} InternalSwitchingEquipment;
			// МС-2М в части АРО
			union TVoiceWarningEquipment {
				struct {
					unsigned char FailVoiceWarning : 1; // Отказ речевого оповещения
				};
				unsigned char alignment[1];
			} VoiceWarningEquipment;
			// радиолокационная система опознавания самолётов и кораблей типа 'свой - чужой' (IFF)
			union TIdentificationFriendFoeSystem {
				struct {
					unsigned char FailCallIFF : 1; // Отказ запросчика
					unsigned char FailAnswerIFF : 1; // Отказ ответчика
					unsigned char GeneralFailure : 1; // Отказ IFF
					unsigned char CryptoComputerFailure : 1; // Отказ криптокомпьютера, нет кодов, компьютер недоступен
					unsigned char RandomizerFailure : 1; // Отказ генертора случайных чисел
					unsigned char NsmNoReply : 1; // Отсутствие ответа NSM
				};
				unsigned char alignment[1];
			} IdentificationFriendFoeSystem;
			// Система отображения информации СОИ (МФИ, ИКШ-1КИ)
			union TDataRepresentationSystem {
				struct {
					unsigned char FailHUD : 1; // Отказ ИКШ
					unsigned char FailMFDLh : 1; // Отказ левого МФИ
					unsigned char FailMFDRh : 1; // Отказ правого МФИ
					unsigned char FailUFCP : 1; // Отказ ПУИ
				};
				unsigned char alignment[1];
			} DataRepresentationSystem;
		} Avionics;
		struct TAircraftEquipment {
			// Система полного и статического давлений
			union TTotalAndStaticPressure {
				struct {
					unsigned char FailPH : 1; // Отказ ПВД
					
					unsigned char MainPitot_NoHeating : 1;// Нет обогр ПВД-18 осн
					unsigned char StandbyPitot_NoHeating : 1;//	Нет обогр ПВД-7 авар

				};
				unsigned char alignment[1];
			} TotalAndStaticPressure;
			// Система автоматического управления САУ-451-05СМТ-И
			union TAutomaticControlSystem {
				struct {
					unsigned char ARUEasyFail : 1; // Отказ АРУ. Шток в положении ЛЕГКО
					unsigned char ARUHeavyFail : 1; // Отказ АРУ. Шток в положении ТЯЖЕЛО
					unsigned char SOSFail : 1; // Самопроизвольный выход штока гидроцилиндра СОС
					unsigned char StabTrimFail : 1; // Отказ триммера стабилизатора
					unsigned char TangageEscape : 1; // Увод по тангажу
					unsigned char BankEscape : 1; // Увод по крену
					unsigned char YawEscape : 1; // Увод по курсу
					unsigned char TangageVibration : 1; // Колебания по тангажу
					unsigned char BankVibration : 1; // Колебания по крену
					unsigned char YawVibration : 1; // Колебания по курсу
					unsigned char APUSFail : 1; // Отказ АПУС
					unsigned char DirFail : 1; // Отказ траекторного управления
					unsigned char AilFailUsePedals : 1; // Отказ элеронов. Управляй педалями
					unsigned char AilFailSAUOff : 1; // Отказ элеронов. Отключи САУ
					unsigned char SAUYawFail : 1; // Отказ канала направления САУ
					unsigned char DamperFail : 1; // Отказ демпфера
					unsigned char SpeedChFLTOff : 1; // ВЛО по скорости отключен
					unsigned char AutopilotModesFail : 1; // Отказ автопилотных режимов САУ
					unsigned char StallLimFail : 1; // Отказ СОС
					unsigned char FLTLimCompFail : 1; // Оказ ВЛО
					unsigned char StallLimRedunFail : 1; // Нет резерва СОС
					unsigned char RecovOff : 1; // Выключение Увода
					unsigned char AutoRecovOff : 1; // Отказ автоматического Увода
					unsigned char SlatsFail : 1; // Отказ канала носковы
				};
				unsigned char alignment[3];
			} AutomaticControlSystem;
			// Система ограничительных сигналов СОС-3М-3 сер.2Н
			union TLimitationSignalSystem {
			};
			// Система электроснабжения постоянным током
			union TElectricSystemDC {
				struct {
					unsigned char FailDCGen : 1; // Отказ генератора постоянного тока
					unsigned char FailDCGenAndVU : 1; // Отказ генератора постоянного тока и выпрямительного устройства
				};
				unsigned char alignment[1];
			} ElectricSystemDC;
			// Система электроснабжения переменным током
			union TElectricSystemAC {
				struct {
					unsigned char FailACGen : 1; // Отказ привод-генератора переменного тока
				};
				unsigned char alignment[1];
			} ElectricSystemAC;
			// Светотехническое оборудование
			union TLightEquipment {
			};
			// Комплексная система контроля и регистрации «Карат-Б-29К-02»
			union TComplexControlSystem {
				struct {
					unsigned char FailKARAT : 1; // Отказ КАРАТ
				};
				unsigned char alignment[1];
			} ComplexControlSystem;
			// Инерциально-спутниковая навигационная система TOTEM-3000
			union TInertialNavigationSystem {
				struct {
					unsigned char FailINS_1 : 1; // Отказ ИНС 1
					unsigned char FailINS_2 : 1; // Отказ ИНС 2
					unsigned char LowINS1accuracy : 1; // Понижение точности ЛИНС-1
					unsigned char LowINS2accuracy : 1; // Понижение точности ЛИНС-2
					unsigned char ReatrtINS1 : 1; // Перезапусти ИНС-1
					unsigned char ReatrtINS2 : 1; // Перезапусти ИНС-2
					unsigned char InputCoord : 1; // Нет достоверных координат  места стоянки
					unsigned char RepeatInput : 1; // Повторить ввод координат места стоянки
					unsigned char OverheatINS1 : 1; // Перегрев ИНС-1
					unsigned char OverheatINS2 : 1; // Перегрев ИНС-2
					unsigned char AclrINS1notReady : 1; // Неготовность прерываемой нормальной выставки ИНС-1
					unsigned char AclrINS2notReady : 1; // Неготовность прерываемой нормальной выставки ИНС-2
				};
				unsigned char alignment[2];
			} InertialNavigationSystem;
			// Система воздушных сигналов СВС-2Ц-У-30МКИ
			union TAirDataSystem {
				struct {
					unsigned char FailADS : 1; // Отказ СВС
				};
				unsigned char alignment[1];
			} AirDataSystem;
			// Самолетное кислородное оборудование и защитное снаряжение летчика
			union TOxygenEquipment {
				struct {
					unsigned char FailOBOGS : 1; // Отказ кислородной системы
					unsigned char CockpitAltLim : 1; // Опасная высота в кабине
				};
				unsigned char alignment[1];
			} OxygenEquipment;
			// Система кислородной подпитки двигателей и турбостартеров
			union TOxygenSupplySystem {
			};
			// Комплекс управления топливомерно – расходомерный
			union TFuelGageFlowmeterSystem {
			};
			// Резервные приборы
			union TStandbyInstruments {
				struct {
					unsigned char FailSTBYhorizon : 1; // Отказ АГР
				};
				unsigned char alignment[1];
			} StandbyInstruments;
			// Бортовая система безопасности полетов
			union TFlightSafetySystem {
				struct {
					unsigned char FltSafetySystFail : 1; // Отказ СБП
				};
				unsigned char alignment[1];
			} FlightSafetySystem;
		} AircraftEquipment;
};
#pragma pack(pop)
// общий размер структуры: 49 байт.
